### ISSUE TITLE
Resultset to DataTable

### ISSUE THREAD

**Issue by ollih1980** [martincooper/java-datatable#5]
Hello @martincooper,

is there a way to import a resultset (java.sql) to DataTable?

Thx a lot!

**Comment by martincooper** [comment]
Hi @ollih1980 

No unfortunately there is not currently a built in way to do this. 

Thanks

**Comment by ollih1980** [comment]
Is there a way to add complete rows to your datatable?
I only figured out how to add columns which includes row data
like : 
IDataColumn StringCol = new DataColumn<>(String.class, "XXX", data);

Something like:
1. create datatable with columns
2. add row-data to colums

Are you getting my point? ;-)

**Comment by martincooper** [comment]
Yes, there certainly is! It's even documented on the front page 😆 

https://github.com/martincooper/java-datatable#adding--updating--deleting-rows

Hopefully that should help 👍

**Comment by ollih1980** [comment]
hmm... okay. So the way should be:

1. create the column with "null" row data
2. add the rows out of Resultset

I will give it a try.

Thx a lot!

**Comment by martincooper** [comment]
You don't need to create a column with "null" row data. Just create a new empty column. You can see example in the first unit test here...

https://github.com/martincooper/java-datatable/blob/master/src/test/java/DataColumnTests.java

EG 
`DataColumn<String> column = new DataColumn<>(String.class, "StringCol");`

**Comment by ollih1980** [comment]
Perfect.  It worked like a charm.

Thanks a lot!

**Comment by martincooper** [comment]
Awesome! 🤩
